##################################################################################################
# dubhe-data-task
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: dubhe-data-task
  labels:
    app: dubhe-data-task
    service: dubhe-data-task
spec:
  type: NodePort
  ports:
  - port: 8801
    name: http
  - port: 5005
    name: debug
  selector:
    app: dubhe-data-task
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dubhe-data-task
  labels:
    account: dubhe-data-task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubhe-data-task-v1
  labels:
    app: dubhe-data-task
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubhe-data-task
      version: v1
  template:
    metadata:
      labels:
        app: dubhe-data-task
        version: v1
    spec:
      serviceAccountName: dubhe-data-task
      containers:
      - name: dubhe-data-task
        image: harbor.test.com/dubhe/dubhe-spring-cloud-k8s:env-value
        imagePullPolicy: Always
        env:
        - name: JAR_BALL
          value: "dubhe-data-task-0.0.1-SNAPSHOT-exec.jar  --spring.profiles.active=env-value"
        - name: JVM_PARAM
          value: "-Xms1024m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=containerLogPath/dubhe-data-task-dump.hprof"
        ports:
        - containerPort: 8801
        - containerPort: 5005
        volumeMounts:
          - mountPath: "fsPath"
            name: "fs-volume"
            readOnly: false
          - mountPath: "containerLogPath"
            name: "log-volume"
            readOnly: false
          - name: "dockersock"
            mountPath: "/var/run/docker.sock"
      volumes:
        - name: "fs-volume"
          hostPath:
            path: "fsPath"
            type: "Directory"
        - name: "log-volume"
          hostPath:
            path: "hostLogPath"
            type: "DirectoryOrCreate"
        - name: "dockersock"
          hostPath:
            path: "/var/run/docker.sock"