##################################################################################################
# admin
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
    service: admin
spec:
  type: NodePort
  ports:
  - port: 8870
    name: http
  selector:
    app: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  labels:
    account: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-v1
  labels:
    app: admin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
      version: v1
  template:
    metadata:
      labels:
        app: admin
        version: v1
    spec:
      serviceAccountName: admin
      containers:
      - name: admin
        image: harbor.test.com/dubhe/dubhe-spring-cloud-k8s:env-value
        imagePullPolicy: Always
        env:
        - name: JAR_BALL
          value: "admin-0.0.1-SNAPSHOT-exec.jar  --spring.profiles.active=env-value"
        - name: JVM_PARAM
          value: "-Xms1024m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=containerLogPath/admin-dump.hprof"
        ports:
        - containerPort: 8870
        volumeMounts:
          - mountPath: "fsPath"
            name: "fs-volume"
            readOnly: false
          - mountPath: "containerLogPath"
            name: "log-volume"
            readOnly: false
          - name: "dockersock"
            mountPath: "/var/run/docker.sock"
      volumes:
        - name: "fs-volume"
          hostPath:
            path: "fsPath"
            type: "Directory"
        - name: "log-volume"
          hostPath:
            path: "hostLogPath"
            type: "DirectoryOrCreate"
        - name: "dockersock"
          hostPath:
            path: "/var/run/docker.sock"