##################################################################################################
# dubhe-train
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: dubhe-train
  labels:
    app: dubhe-train
    service: dubhe-train
spec:
  type: NodePort
  ports:
    - port: 8890
      name: http
  selector:
    app: dubhe-train
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dubhe-train
  labels:
    account: dubhe-train
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubhe-train-v1
  labels:
    app: dubhe-train
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubhe-train
      version: v1
  template:
    metadata:
      labels:
        app: dubhe-train
        version: v1
    spec:
      serviceAccountName: dubhe-train
      containers:
        - name: dubhe-train
          image: harbor.test.com/dubhe/dubhe-spring-cloud-k8s:env-value
          imagePullPolicy: Always
          env:
            - name: JAR_BALL
              value: "dubhe-train-0.0.1-SNAPSHOT-exec.jar  --spring.profiles.active=env-value"
            - name: JVM_PARAM
              value: "-Xms1024m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=containerLogPath/dubhe-train-dump.hprof"
          ports:
            - containerPort: 8890
          volumeMounts:
            - mountPath: "fsPath"
              name: "fs-volume"
              readOnly: false
            - mountPath: "containerLogPath"
              name: "log-volume"
              readOnly: false
            - name: "dockersock"
              mountPath: "/var/run/docker.sock"
      volumes:
        - name: "fs-volume"
          hostPath:
            path: "fsPath"
            type: "Directory"
        - name: "log-volume"
          hostPath:
            path: "hostLogPath"
            type: "DirectoryOrCreate"
        - name: "dockersock"
          hostPath:
            path: "/var/run/docker.sock"