spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: prod

  application:
    name: dataset-util
  # 配置Sharding-JDBC数据源名称，可配置多个
  shardingsphere:
    datasource:
      name: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        test-while-idle: true
        validation-query: select 1
        # 初始化配置
        initial-size: 3
        # 最小连接数
        min-idle: 3
        # 最大连接数
        max-active: 15
        # 获取连接超时时间
        max-wait: 5000
        # 连接有效性检测时间
        time-between-eviction-runs-millis: 90000
        # 最大空闲时间
        min-evictable-idle-time-millis: 1800000
        test-on-borrow: false
        test-on-return: false

    #指定data_dataset表 主键id 生成策略
    sharding:
      tables:
        data_file:
          actual-data-nodes: master.data_file_$->{1..300}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.datasetutil.common.util.MyPreciseShardingAlgorithm

        data_dataset_version_file:
          actual-data-nodes: master.data_dataset_version_file_$->{1..300}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.datasetutil.common.util.MyPreciseShardingAlgorithm

        data_file_annotation:
          actual-data-nodes: master.data_file_annotation_$->{1..300}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.datasetutil.common.util.MyPreciseShardingAlgorithm
      props:
        sql:
          show: true

minio:
  secure: false
  blockingCoefficient: 0.5

#logback
logging.config:
  classpath:logback-spring-${spring.profiles.active}.xml

mybatis-plus:
  global-config:
    banner: false

# ES服务地址及端口
es:
  host: 127.0.0.1
  serverPort: 9200
  transportPort: 9300
  index: dataset_text_test