spring:
  application:
    name: serving-gateway
  profiles:
    active: @profileActive@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#      routes:
#      - id: weight_high
#        uri: https://weighthigh.org
#        predicates:
#          - Weight=group1, 8
#      - id: weight_low
#        uri: https://weightlow.org
#        predicates:
#          - Weight=group1, 2
#      - id: my_route   #路由的ID，没有固定规则但要求唯一，建议配合服务名
#        uri: http://baidu.com #匹配后提供服务的路由地址
#        predicates:
#          - Path=/get         # 断言，路径相匹配的进行路由

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.dubhe.domain.entity    # 所有Entity别名类所在包

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
